In [1]:
import numpy as np

In [2]:
N = 8

In [3]:
board_state_memory = {}

In [4]:
board = np.zeros((N,N),dtype=np.int8)

In [5]:
board

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [6]:
def create_board_string(board):
    board_string = ''
    for i in range(N):
        for j in range(N):
            board_string += str(board[i][j])
    return board_string

In [7]:
create_board_string(board)

'0000000000000000000000000000000000000000000000000000000000000000'

In [8]:
board_copy = board.copy()
board_copy[0,1] = 1

In [9]:
create_board_string(board_copy)

'0100000000000000000000000000000000000000000000000000000000000000'

In [87]:
def is_board_safe(board):
    
    board_key = create_board_string(board)
    
    if board_key in board_state_memory:
        print('Using cached information')
        return board_state_memory[board_key]
    
    row_sum = np.sum(board, axis=1)
    if len(row_sum[np.where(row_sum>1)]) > 0:
        board_state_memory[board_key] = False
        return False
    
    col_sum = np.sum(board, axis=0)
    if len(col_sum[np.where(col_sum>1)]) > 0:
        board_state_memory[board_key] = False
        return False
    
    diags = [board[::-1,:].diagonal(i) for i in range(-board.shape[0] + 1, board.shape[1])]
    
    diags.extend(board.diagonal(i) for i in range(board.shape[1] - 1, -board.shape[0], -1))
    
    for diag in diags:
        if np.sum(diag) > 1:
            board_state_memory[board_key] = False
            return False
        
    board_state_memory[board_key] = True
    return True

In [88]:
board_copy = board.copy()

In [89]:
board_copy[0][0] = 1
board_copy[0][5] = 1

In [90]:
print(board_copy)
is_board_safe(board_copy)

[[1 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


False

In [91]:
board_copy = board.copy()

In [92]:
board_copy[2][4] = 1
board_copy[5][4] = 1

In [93]:
print(board_copy)
is_board_safe(board_copy)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


False

In [94]:
board_copy = board.copy()

In [95]:
board_copy[1][0] = 1
board_copy[2][3] = 1
board_copy[0][1] = 1

In [96]:
print(board_copy)
is_board_safe(board_copy)

[[0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


False

In [97]:
def place_queen(board, column):
    if column >= N:
        return True
    
    for row in range(N):
        board[row][column] = 1
        
        safe = False
        if is_board_safe(board):
            safe = place_queen(board, column + 1)
        
        if not safe:
            board[row][column] = 0
        else : 
            break
            
    return safe  

In [98]:
board_state_memory

{'1000010000000000000000000000000000000000000000000000000000000000': False,
 '0000000000000000000010000000000000000000000010000000000000000000': False,
 '0100000010000000000100000000000000000000000000000000000000000000': False}

In [99]:
board = np.zeros((N,N), np.int8)
placed = place_queen(board, 0)
print(placed)

True


In [100]:
board

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0]], dtype=int8)

In [75]:
board_state_memory

{'1000010000000000000000000000000000000000000000000000000000000000': False,
 '0000000000000000000010000000000000000000000010000000000000000000': False,
 '0100000010000000000100000000000000000000000000000000000000000000': False,
 '1000000000000000000000000000000000000000000000000000000000000000': True,
 '0000000010000000000000000000000000000000000000000000000000000000': True,
 '0000000000000000100000000000000000000000000000000000000000000000': True,
 '0000000000000000000000001000000000000000000000000000000000000000': True,
 '0000000000000000000000000000000010000000000000000000000000000000': True,
 '0000000000000000000000000000000000000000100000000000000000000000': True,
 '0000000000000000000000000000000000000000000000001000000000000000': True,
 '0000000000000000000000000000000000000000000000000000000010000000': True}

In [101]:
board = np.zeros((N,N), np.int8)
placed = place_queen(board, 0)
print(placed)

Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information


Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information


In [110]:
board

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0]], dtype=int8)